Makefile: call cc-disable-warning to disable some warnings
following error by clang:
error: unknown warning option '-Wno-undefined-optimized'; did you mean '-Wno-undefined-inline'? [-Werror,-Wunknown-warning-option]

Fixes: 2ba37a00a2a2353e2929e48c789a7f6a38463ef1 ("Makefile: Disable undefined-optimized and tautological features")
Change-Id: Ifbb51668751f1a1696c8be8d1d1db6af880df7d9