Revert "drivers: touchscreen: Fix empty-body warnings"
* GCC doesnt like this.

../../../../../../kernel/xiaomi/tulip/drivers/input/touchscreen/nvt_touch_a/nt36xxx.c: In function 'nvt_gesture_write':
../../../../../../kernel/xiaomi/tulip/drivers/input/touchscreen/nvt_touch_a/nt36xxx.c:149:2: error: ignoring return value of 'copy_from_user', declared with attribute warn_unused_result [-Werror=unused-result]
  copy_from_user(&str, buf, 1);
  ^
cc1: all warnings being treated as errors

This reverts commit ee4e1be3dfa205a74bd6f9ee1ca2d33679bb6e45.